{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xapp_core.fullname" . }}
  labels:
    {{- include "xapp_core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name:  "generic"
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
    - port: 8888
      name: "restapi"
  selector:
    {{- include "xapp_core.selectorLabels" . | nindent 4 }}
{{- end }}
